local plugin_label = 'alfred_the_butler'
-- kept plugin label instead of waiting for update_tracker to set it

local tracker = {
    name                      = plugin_label,
    version                   = nil,
    inventory_full            = false,
    inventory_count           = 0,
    salvage_count             = 0,
    sell_count                = 0,
    stash_count               = 0,
    trigger_tasks             = false,
    last_reset                = 0,
    salvage_failed            = false,
    salvage_done              = false,
    sell_failed               = false,
    sell_done                 = false,
    repair_failed             = false,
    repair_done               = false,
    stash_failed              = false,
    stash_done                = false,
    all_task_done             = false,
    external_caller           = nil,
    external_trigger          = false,
    external_trigger_callback = nil,
    external_pause            = false,
    teleport                  = false,
    teleport_done             = false,
    teleport_failed           = false,
    manual_trigger            = false,
    restock_items             = {},
    restock_failed            = false,
    restock_done              = false,
    restock_count             = 0,
    last_task                 = 'status',
    previous                  = {},
    stash_socketables         = false,
    stash_keys                = false,
    stash_boss_materials      = false,
    cached_inventory          = {},
    stocktake                 = false,
    stocktake_done            = false,
    stocktake_failed          = false,
    need_repair               = false,
    need_trigger              = false,
    need_stash_socketables    = false,
    need_stash_consumables    = false,
    need_stash_keys           = false,
    need_gamble               = false,
    gamble_done               = false,
    gamble_failed             = false,
    gamble_paused             = false,
    gambling                  = false,
}

return tracker